name: dispatch

on:
   workflow_dispatch:
      inputs:
         logLevel:
            description: 'test'     
            required: true
            default: 'warning'
         tags:
            description: 'Test scenario tags'


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Check out
        uses: actions/checkout@v2
